<a href="https://colab.research.google.com/github/Timothy-John-Kaharian/CSST101-Activities/blob/main/Lesson_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **My First R Program**

In [ ]:
print("Hello World")

[1] "Hello World"

## **1. Print**

In [ ]:
myString <- ("Hello World2")

print(myString)

[1] "Hello World2"

## **2. Data Type**

In [ ]:
myString <- ("Hellow World3")
num <- 10
floatingNum <- 9.5
isBool <- TRUE

class(myString)
class(num)
class(floatingNum)
class(isBool)

print(myString)
print(num)
print(floatingNum)
print(isBool)

ERROR: Error in parse(text = input): <text>:11:8: unexpected symbol
10:
11: print(\n
           ^

## **3. Numeric Operation**

In [ ]:
x <- 5
y <- 3

sum <- x + y
subtract <- x - y
mult <- x * y
div <- x / y

print(paste0("The + is ", sum))
print(paste0("The - is ", subtract))
print(paste0("The * is ", mult))
print(paste0("The / is ", div))

cat(paste0("\nThe + is ", sum, "\n"))
cat(paste0("The - is ", subtract, "\n"))
cat(paste0("The * is ", mult, "\n"))
cat(paste0("The / is ", div, "\n"))

[1] "The + is 8"
[1] "The - is 2"
[1] "The * is 15"
[1] "The / is 1.66666666666667"

The + is 8
The - is 2
The * is 15
The / is 1.66666666666667

## **4. USER INPUT**

In [ ]:
name <- readline("Enter Name: ")

cat(paste0("\nName: ", name , "\n"))

Enter Name: Timothy John R. Kaharian

Name: Timothy John R. Kaharian

## **5. Decision Making**

In [ ]:
grade <- 80

if (grade < 75) {
  print("Failed")
} else {
  print("Passed")
}

[1] "Passed"

## **6. Loop**

In [ ]:
for (i in 1:10){
  cat(i, "\n")
}

1
2
3
4
5
6
7
8
9
10

## **7. Functions**

In [ ]:
addNumber <- function(a, b){
  return(a + b)
}

addNumber(10, 10)

[1] 20

## **8. Vectors**

In [ ]:
grades <- c(75, 80, 90, 100)


cat(paste0("Mean: ", mean(grades) ))
cat(paste0("\nMAX: ", max(grades) ))
cat(paste0("\nMIN: ", min(grades) ))
cat(paste0("\nSUM: ", sum(grades) ))
cat(paste0("\nLENGTH: ", length(grades) ))

Mean: 86.25
MAX: 100
MIN: 75
SUM: 345
LENGTH: 4

## **9. Matrices**

In [ ]:
A <- matrix(c(1,2,3,4,5,6), nrow = 2)

A

     [,1] [,2] [,3]
[1,] 1    3    5
[2,] 2    4    6

## **10. List**

In [ ]:
student <- list(
  name = "Tim",
  age = 21,
  GPA = 1.5
)

student

$name
[1] "Tim"

$age
[1] 21

$GPA
[1] 1.5

## **11. Data Frames and Write CSV**

In [ ]:
students <- data.frame(
  Name = c("John", "Mary", "Anna"),
  Age = c(20, 21, 19),
  GPA = c(1.2, 1.8, 1.4)
)

students

write.csv(students, "student.csv")

  Name Age GPA
1 John 20  1.2
2 Mary 21  1.8
3 Anna 19  1.4

## **12. Reading CSV Files**

In [ ]:
data <- read.csv("student.csv")

head(data)
summary(data)

  X Name Age GPA
1 1 John 20  1.2
2 2 Mary 21  1.8
3 3 Anna 19  1.4

       X              Name        Age            GPA
 Min.   :1.0   Length   :3   Min.   :19.0   Min.   :1.200
 1st Qu.:1.5   N.unique :3   1st Qu.:19.5   1st Qu.:1.300
 Median :2.0   N.blank  :0   Median :20.0   Median :1.400
 Mean   :2.0   Min.nchar:4   Mean   :20.0   Mean   :1.467
 3rd Qu.:2.5   Max.nchar:4   3rd Qu.:20.5   3rd Qu.:1.600
 Max.   :3.0                 Max.   :21.0   Max.   :1.800